spring:
  config:
    import: private.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://limla.ml:3306/tiremanagement?createDatabaseIfNotExist=true&serverTimezone=CET
    driver:-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-message: always
  port: 8080
