spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://limla.ml:3306/tiremanagement?createDatabaseIfNotExist=true&serverTimezone=CET
    driver:-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}

app:
  jwtSecret: ${JWT.SECRET}
  jwtExpirationInMs: ${JWT.EXPIRATION}

server:
  ssl:
    key-store: keystore.p12
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true
    key-store-password: ${KEY.STORE.PASSWORD}
  port: 8443
  error:
    include-message: always