spring:
  config:
    import: private.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://limla.ml:3306/tiremanagement?createDatabaseIfNotExist=true&serverTimezone=CET
    driver:-class-name: com.mysql.cj.jdbc.Driver

server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-type: pkcs12
    key-alias: springboot
    enabled: true
  port: 8443
  error:
    include-message: always