name: Maven Build and Docker deploy on Remote

on:
  workflow_dispatch:
  
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
           
    - name: print dir
      run: pwd
    - name: list files
      run: ls -la
    - name: list target
      run: ls -la target/
