name: Maven Build and Docker deploy on Remote

on:
  push:
    branches: dev
  
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
           
    - name: print dir
      run: pwd
    - name: list files
      run: ls -la
    - name: list target
      run: ls -la target/
    - name: secure copy target
      run: sshpass -p ${{secrets.SSH_PASSWORD}} scp -r -P ${{secrets.SSH_PORT}} ./target/tiremanagement-0.0.1.jar ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/docky/tiremanagementRestApi/restapi.jar
