name: Maven Build and Docker deploy on Remote

on:
  workflow_dispatch:
  
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
           
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/tiremanagement-0.0.1.jar"
        target: "/home/docky/tiremanagementRestApi/restapi.jar"
