name: Maven CI/CD

on:
  workflow_dispatch:
  
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
           
    - name: Upload Files
      uses: siva1024/scp-deployer@latest
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD}}
        source: "./target/tiremanagement-0.0.1.jar"
        target: "/home/docky/tiremanagementRestApi/restapi.jar"
