name: Maven Build and Docker deploy on Remote

on:
  workflow_dispatch:
  
jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
           
    - name: scp files
    - run: pwd
    - run: ls
    - run: ls target/
    - run: sshpass -p ${{secrets.SSH_PASSWORD}} scp -r -P ${{secrets.SSH_PORT}} ./target/tiremanagement-0.0.1.jar ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/docky/tiremanagementRestApi/restapi.jar
        
    - name: deploy docker
      run: |
        - sshpass -p ${{secrets.SSH_PASSWORD}} ssh -r -p ${{secrets.SSH_PORT}} ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}
        - cd /home/docky/tiremanagementRestApi/
        - docker-compose down
        - docker-compose build
        - docker-compose up -d
